version: 0.1
log:
  level: warn
http:
  addr: :5000
proxy:
  remoteurl: https://registry-1.docker.io
  username: lucas42
  ttl: 168h
storage:
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
