services:
  registry:
    image: registry:2
    container_name: lucos_docker_mirror_registry
    environment:
      - REGISTRY_LOG_LEVEL=warn
      - REGISTRY_HTTP_ADDR=:5000
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
      - REGISTRY_PROXY_USERNAME=lucas42
      - REGISTRY_PROXY_PASSWORD
      - REGISTRY_PROXY_TTL=168h
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_ENABLED=true
      - REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_AGE=168h
      - REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_INTERVAL=24h
      - REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_DRYRUN=false
    volumes:
      - cache:/var/lib/registry
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "http://127.0.0.1:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    image: lucas42/lucos_docker_mirror_web:${VERSION}
    container_name: lucos_docker_mirror_web
    environment:
      - PORT
      - SYSTEM
      - ENVIRONMENT
      - REGISTRY_CLIENT_USERNAME
      - REGISTRY_CLIENT_PASSWORD
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - cache:/var/lib/registry:ro
    depends_on:
      registry:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT}/_info"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cache:
