services:
  registry:
    build:
      context: .
      dockerfile: registry.Dockerfile
    image: lucas42/lucos_docker_mirror_registry:${VERSION:-latest}
    container_name: lucos_docker_mirror_registry
    environment:
      - REGISTRY_PROXY_PASSWORD
    volumes:
      - cache:/var/lib/registry
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "http://127.0.0.1:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3

  info:
    build:
      context: ./info
    image: lucas42/lucos_docker_mirror_info:${VERSION:-latest}
    container_name: lucos_docker_mirror_info
    environment:
      - SYSTEM
      - ENVIRONMENT
    volumes:
      - cache:/var/lib/registry:ro
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/_info"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    image: lucas42/lucos_docker_mirror_web:${VERSION:-latest}
    container_name: lucos_docker_mirror_web
    environment:
      - PORT
      - REGISTRY_CLIENT_USERNAME
      - REGISTRY_CLIENT_PASSWORD
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      registry:
        condition: service_healthy
      info:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT}/_info"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  cache:
